In [1]:
import pandas as pd
import numpy as np

# DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2.4,3],[2,6,4]])
a2

array([[1. , 2.4, 3. ],
       [2. , 6. , 4. ]])

In [4]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [9]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

df= pd.DataFrame(a2)
df

# 2. Creating Arrays

### Creating 'ones' array

In [12]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [13]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Creating array of Zeros

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Creating an array using arange

In [15]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

# Random integer Array

In [16]:
random_array=np.random.randint(0,10, size=(3,5))
random_array

array([[6, 3, 5, 3, 8],
       [1, 8, 9, 9, 1],
       [1, 5, 1, 5, 4]])

# Random Array

In [17]:
ra=np.random.random((5,3))
ra

array([[0.77554619, 0.31885169, 0.848155  ],
       [0.42278546, 0.19213713, 0.46565208],
       [0.14048865, 0.05642989, 0.72797062],
       [0.75362349, 0.29682918, 0.89810891],
       [0.95910952, 0.00368261, 0.49372142]])

# Creating Array using 'Rand'

In [18]:
ra1=np.random.rand(5,3)
ra1

array([[0.52373099, 0.60448318, 0.42498146],
       [0.91989423, 0.38710839, 0.86025386],
       [0.05310023, 0.45565656, 0.37846511],
       [0.42652166, 0.48384119, 0.0821129 ],
       [0.86379775, 0.79160655, 0.72124004]])