In [1]:
import pandas as pd
import numpy as np

# DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2.4,3],[2,6,4]])
a2

array([[1. , 2.4, 3. ],
       [2. , 6. , 4. ]])

In [4]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [9]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

df= pd.DataFrame(a2)
df

# 2. Creating Arrays

### Creating 'ones' array

In [12]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [13]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Creating array of Zeros

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Creating an array using arange

In [15]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

# Random integer Array

In [16]:
random_array=np.random.randint(0,10, size=(3,5))
random_array

array([[5, 0, 1, 5, 2],
       [5, 7, 1, 3, 5],
       [6, 3, 9, 4, 3]])

# Random Array

In [17]:
ra=np.random.random((5,3))
ra

array([[0.52899537, 0.90480407, 0.22277528],
       [0.03358894, 0.94203235, 0.01204148],
       [0.04097564, 0.64804913, 0.93760875],
       [0.0176948 , 0.59665099, 0.60573358],
       [0.07509445, 0.60488771, 0.6073618 ]])

# Creating Array using 'Rand'

In [18]:
ra1=np.random.rand(5,3)
ra1

array([[0.70636687, 0.05758882, 0.27508889],
       [0.43049309, 0.43725072, 0.10512038],
       [0.82284541, 0.38699877, 0.52070736],
       [0.33561717, 0.77753421, 0.59206617],
       [0.94272897, 0.55930842, 0.34641742]])

# Random Seed

In [19]:
np.random.seed(seed=42)
ra2=np.random.randint(10,size=(5,3))
ra2

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

# Finding unique elements of an array 

In [20]:
np.unique(ra2)

array([2, 3, 4, 5, 6, 7, 9])

In [21]:
ra2[3]

array([4, 3, 7])

In [22]:
ra2.shape

(5, 3)

In [23]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [24]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [25]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 1, 7, 5, 1],
         [4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6]],

        [[4, 8, 6, 1, 3],
         [8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7]],

        [[3, 1, 5, 5, 9],
         [3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7]]],


       [[[9, 8, 8, 0, 8],
         [6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6]],

        [[9, 8, 6, 8, 7],
         [1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0]],

        [[4, 9, 6, 6, 8],
         [9, 9, 2, 6, 0],
         [3, 3, 4, 6, 6],
         [3, 6, 2, 5, 1]]]])

In [26]:
a4[:,:,:,:3]

array([[[[4, 1, 7],
         [4, 0, 9],
         [0, 9, 2],
         [8, 2, 4]],

        [[4, 8, 6],
         [8, 1, 9],
         [4, 1, 3],
         [2, 0, 3]],

        [[3, 1, 5],
         [3, 5, 1],
         [9, 3, 7],
         [7, 4, 1]]],


       [[[9, 8, 8],
         [6, 8, 7],
         [7, 2, 0],
         [2, 0, 4]],

        [[9, 8, 6],
         [1, 0, 6],
         [4, 2, 7],
         [0, 2, 4]],

        [[4, 9, 6],
         [9, 9, 2],
         [3, 3, 4],
         [3, 6, 2]]]])

# Manipulating and Comparing Arrays

### Arithmetic

In [27]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [28]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [29]:
a2= a1+ones
a2

array([2., 3., 4.])

In [30]:
a1/ones

array([1., 2., 3.])

In [31]:
a2/a1

array([2.        , 1.5       , 1.33333333])

In [32]:
a2//a1

array([2., 1., 1.])

In [33]:
a2**2

array([ 4.,  9., 16.])

In [34]:
a1%2

array([1, 0, 1])

In [35]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [36]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [37]:
a1

array([1, 2, 3])

In [38]:
sum(a1)

6

In [39]:
massive_array=np.random.random(100000)
massive_array.size

100000

In [40]:
massive_array[:10]

array([0.62435405, 0.29563369, 0.10549426, 0.45653457, 0.21844044,
       0.41650995, 0.88328026, 0.32434502, 0.12208795, 0.35629784])

In [41]:
%timeit sum(massive_array)   # Python's sum()
%timeit np.sum(massive_array)   # numpy's sum

7.11 ms ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.9 µs ± 42.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [42]:
np.max(massive_array)

0.9999738676462568

### Standard Deviation

In [43]:
np.std(massive_array)

0.28845427228313797

# Variation

In [44]:
np.var(massive_array)

0.08320586719839469

# Sqrt of variation is standard deviation

In [45]:
std=np.sqrt(np.var(massive_array))
std

0.28845427228313797

## Reshaping & Transposing

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3.shape

(2, 3, 3)

In [48]:
a2

array([2., 3., 4.])

In [49]:
a2.shape

(3,)

In [50]:
a2.reshape(1,3)

array([[2., 3., 4.]])

In [51]:
a4 = np.array([[1,2,3],[4,5,6]])
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a4.shape

(2, 3)

In [53]:
a4.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
# a3*a4

In [56]:
a4.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [57]:
a3*a4.reshape(2,3,1)

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

# Transpose

In [58]:
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a4.shape

(2, 3)

In [60]:
a4.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
a4.T.shape

(3, 2)

# Dot Product

In [62]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [63]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [64]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [65]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [66]:
# np.dot(mat1,mat2)

In [67]:
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Nut Butter Sales

In [68]:
a = np.array([[2,7,1],[9,4,16],[11,14,18],[13,13,16],[15,18,9]])
a

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [69]:
a.shape

(5, 3)

In [70]:
b=np.array([10,8,12])
b

array([10,  8, 12])

In [71]:
b.shape

(3,)

In [72]:
np.dot(a,b)

array([ 88, 314, 438, 426, 402])

In [73]:
weekly_sales=pd.DataFrame(a,index = ['Mon','Tues', 'Wed','Thurs','Fri'],columns=['Almond_butter','Peanut_butter','Cashew_butter'])
weekly_sales

Almond_butter  Peanut_butter  Cashew_butter
Mon                2              7              1
Tues               9              4             16
Wed               11             14             18
Thurs             13             13             16
Fri               15             18              9

In [74]:
Price=b
Price

array([10,  8, 12])

In [75]:
Butter_prices=pd.DataFrame(Price.reshape(1,3),index=['Price'],columns=['Almond_butter','Peanut_butter','Cashew_butter'])
Butter_prices

Almond_butter  Peanut_butter  Cashew_butter
Price             10              8             12

In [76]:
Total_Sales = np.dot(weekly_sales,Price.T)
Total_Sales

array([ 88, 314, 438, 426, 402])

In [77]:
weekly_sales.shape, Butter_prices.shape

((5, 3), (1, 3))

In [78]:
weekly_sales['Total($)']=Total_Sales

In [79]:
weekly_sales

Almond_butter  Peanut_butter  Cashew_butter  Total($)
Mon                2              7              1        88
Tues               9              4             16       314
Wed               11             14             18       438
Thurs             13             13             16       426
Fri               15             18              9       402

# Comparison Operator

In [80]:
a1

array([1, 2, 3])

In [81]:
a4

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a1>a4

array([[False, False, False],
       [False, False, False]])

In [83]:
a1>=a4

array([[ True,  True,  True],
       [False, False, False]])

# Sorting the Arrays

In [84]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [85]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [86]:
np.sort(random_array)

array([[1, 2, 3, 3, 8],
       [0, 1, 3, 3, 7],
       [0, 4, 7, 9, 9]])

In [87]:
np.argmax(random_array,axis=0)

array([2, 2, 0, 2, 2])

In [88]:
np.argmax(random_array,axis=1)

array([2, 2, 0])